build: off

environment:
  nodejs_version: "7.8.0"

install:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_test:
  - node --version
  - npm --version

test_script:
  - npm run test:ci
